version: '2'
services:
    jhipster_bookmarks-app:
        image: jhipster_bookmarks
        external_links:
            - jhipster_bookmarks-postgresql:postgresql
            - jhipster_bookmarks-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhipster_bookmarks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhipster_bookmarks-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster_bookmarks-postgresql
    jhipster_bookmarks-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipster_bookmarks-elasticsearch
