version: '2'
services:
    jhipster_bookmarks-sonar:
        container_name: jhipster_bookmarks-sonar
        image: sonarqube:5.5-alpine
        ports:
            - 9000:9000
            - 9092:9092
